
CC =	gcc
CFLAGS =  
CPP =	
LINK =	$(CC)


single_linked_list:
	${CC} single_linked_list.c -o single_linked_list

double_linked_list:
	${CC} double_linked_list.c -o double_linked_list


clean:
	rm -f single_linked_list

